class Constants:
    NOT_AT_RISK_THRESHOLD = 90
    MODERATE_RISK_THRESHOLD = 70
    AT_RISK_THRESHOLD = 50

    LOGIN_WEIGHT = 0.25
    FEATURE_ADOPTION_WEIGHT = 0.25
    SUPPORT_TICKET_WEIGHT = 0.2
    INVOICE_WEIGHT = 0.2
    API_USAGE_WEIGHT = 0.1