"""change ApiUsage model

Revision ID: 545714f9c428
Revises: 6d0c72667c4d
Create Date: 2025-09-12 22:22:01.164964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545714f9c428'
down_revision = '6d0c72667c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_endpoint', sa.String(), nullable=False))
        batch_op.drop_column('call_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('call_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('api_endpoint')

    # ### end Alembic commands ###
